// Copyright 2026 jbellsolutions and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCompaniesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "companies",
		Short:       "List, get, create, and update companies",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCompaniesCreateCompanyCmd(flags))
	cmd.AddCommand(newCompaniesGetCompanyCmd(flags))
	cmd.AddCommand(newCompaniesListCmd(flags))
	cmd.AddCommand(newCompaniesUpdateCompanyCmd(flags))
	cmd.AddCommand(newCompaniesAgentsCmd(flags))
	cmd.AddCommand(newCompaniesImportsCmd(flags))
	cmd.AddCommand(newCompaniesIssuesCmd(flags))
	cmd.AddCommand(newCompaniesProjectsCmd(flags))
	cmd.AddCommand(newCompaniesRoutinesCmd(flags))
	return cmd
}
