// Copyright 2026 jbellsolutions and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCompaniesAgentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "agents",
		Short:       "List and create agents for companies",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCompaniesAgentsCreateCmd(flags))
	cmd.AddCommand(newCompaniesAgentsListCmd(flags))
	return cmd
}
