// Copyright 2026 jbellsolutions and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newIssuesCommentsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "comments",
		Short:       "List and add comments for issues",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newIssuesCommentsAddCmd(flags))
	cmd.AddCommand(newIssuesCommentsListCmd(flags))
	return cmd
}
