// Copyright 2026 jbellsolutions and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRoutinesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "routines",
		Short:       "Get and update routines",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRoutinesGetCmd(flags))
	cmd.AddCommand(newRoutinesUpdateCmd(flags))
	return cmd
}
