// Copyright 2026 jbellsolutions and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"gov-pp-cli/internal/cli"
	"gov-pp-cli/internal/client"
	"gov-pp-cli/internal/cliutil"
	"gov-pp-cli/internal/config"
	"gov-pp-cli/internal/mcp/cobratree"
	"gov-pp-cli/internal/store"
)

const (
	mcpToolResultMaxBytes = 60000
	mcpToolResultMaxItems = 50
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("agents_delete",
			mcplib.WithDescription("Delete an agent (managers with reports may 500 — set status=terminated instead). Required: agentId. Destructive."),
			mcplib.WithString("agentId", mcplib.Required(), mcplib.Description("Agent id")),
			mcplib.WithDestructiveHintAnnotation(true),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("DELETE", "/api/agents/{agentId}", false, false, nil, []mcpParamBinding{{PublicName: "agentId", WireName: "agentId", Location: "path"}}, []string{"agentId"}),
	)
	s.AddTool(
		mcplib.NewTool("agents_get",
			mcplib.WithDescription("Read an agent (incl. stats). Required: agentId."),
			mcplib.WithString("agentId", mcplib.Required(), mcplib.Description("Agent id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/agents/{agentId}", true, false, nil, []mcpParamBinding{{PublicName: "agentId", WireName: "agentId", Location: "path"}}, []string{"agentId"}),
	)
	s.AddTool(
		mcplib.NewTool("agents_update",
			mcplib.WithDescription("Update an agent (status, budget, adapter, reporting line). Required: agentId. Optional: adapterConfig, adapterType, budgetMonthlyCents (plus 3 more). Partial update."),
			mcplib.WithString("agentId", mcplib.Required(), mcplib.Description("Agent id")),
			mcplib.WithString("adapter-config-cwd", mcplib.Description("Cwd")),
			mcplib.WithString("adapter-config-env", mcplib.Description("Env")),
			mcplib.WithString("adapter-config-model", mcplib.Description("Model")),
			mcplib.WithString("adapterType", mcplib.Description("Adapter type")),
			mcplib.WithNumber("budgetMonthlyCents", mcplib.Description("Budget monthly cents")),
			mcplib.WithString("reportsTo", mcplib.Description("Reports to")),
			mcplib.WithString("status", mcplib.Description("Status")),
			mcplib.WithString("title", mcplib.Description("Title")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/api/agents/{agentId}", false, false, nil, []mcpParamBinding{{PublicName: "agentId", WireName: "agentId", Location: "path"}, {PublicName: "adapter-config-cwd", WireName: "cwd", Location: "body", BodyPath: []string{"adapterConfig", "cwd"}}, {PublicName: "adapter-config-env", WireName: "env", Location: "body", BodyPath: []string{"adapterConfig", "env"}}, {PublicName: "adapter-config-model", WireName: "model", Location: "body", BodyPath: []string{"adapterConfig", "model"}}, {PublicName: "adapterType", WireName: "adapterType", Location: "body"}, {PublicName: "budgetMonthlyCents", WireName: "budgetMonthlyCents", Location: "body"}, {PublicName: "reportsTo", WireName: "reportsTo", Location: "body"}, {PublicName: "status", WireName: "status", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}}, []string{"agentId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_create-company",
			mcplib.WithDescription("Create a company (a new business). Required: name. Optional: description, metadata."),
			mcplib.WithString("description", mcplib.Description("Description")),
			mcplib.WithString("metadata", mcplib.Description("Metadata")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/companies", false, false, nil, []mcpParamBinding{{PublicName: "description", WireName: "description", Location: "body"}, {PublicName: "metadata", WireName: "metadata", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("companies_get-company",
			mcplib.WithDescription("Read a company (incl. budget/spend). Required: companyId."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/companies/{companyId}", true, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_list",
			mcplib.WithDescription("List all companies."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/companies", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("companies_update-company",
			mcplib.WithDescription("Update a company (rename, budget, archive). Required: companyId. Optional: budgetMonthlyCents, description, name (plus 1 more). Partial update."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithNumber("budgetMonthlyCents", mcplib.Description("Budget monthly cents")),
			mcplib.WithString("description", mcplib.Description("Description")),
			mcplib.WithString("name", mcplib.Description("Name")),
			mcplib.WithString("status", mcplib.Description("Status")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/api/companies/{companyId}", false, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}, {PublicName: "budgetMonthlyCents", WireName: "budgetMonthlyCents", Location: "body"}, {PublicName: "description", WireName: "description", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "status", WireName: "status", Location: "body"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_agents_create",
			mcplib.WithDescription("Create an agent (team member). Required: companyId, adapterType (default: opencode_local), name. Optional: adapterConfig, budgetMonthlyCents (default: 0), reportsTo (plus 2 more)."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithString("adapter-config-cwd", mcplib.Description("Cwd")),
			mcplib.WithString("adapter-config-env", mcplib.Description("Env")),
			mcplib.WithString("adapter-config-model", mcplib.Description("Model")),
			mcplib.WithString("adapterType", mcplib.Required(), mcplib.Description("Adapter type")),
			mcplib.WithNumber("budgetMonthlyCents", mcplib.Description("Budget monthly cents")),
			mcplib.WithString("name", mcplib.Required(), mcplib.Description("Name")),
			mcplib.WithString("reportsTo", mcplib.Description("Reports to")),
			mcplib.WithString("role", mcplib.Description("Role")),
			mcplib.WithString("title", mcplib.Description("Title")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/companies/{companyId}/agents", false, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}, {PublicName: "adapter-config-cwd", WireName: "cwd", Location: "body", BodyPath: []string{"adapterConfig", "cwd"}}, {PublicName: "adapter-config-env", WireName: "env", Location: "body", BodyPath: []string{"adapterConfig", "env"}}, {PublicName: "adapter-config-model", WireName: "model", Location: "body", BodyPath: []string{"adapterConfig", "model"}}, {PublicName: "adapterType", WireName: "adapterType", Location: "body"}, {PublicName: "budgetMonthlyCents", WireName: "budgetMonthlyCents", Location: "body"}, {PublicName: "name", WireName: "name", Location: "body"}, {PublicName: "reportsTo", WireName: "reportsTo", Location: "body"}, {PublicName: "role", WireName: "role", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_agents_list",
			mcplib.WithDescription("List a company's agents. Required: companyId."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/companies/{companyId}/agents", true, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_imports_apply",
			mcplib.WithDescription("Import a team/business package (github subdir tree URL, or inline files) as a new or existing company. Required: companyId, source, target. Optional: adapterOverrides, collisionStrategy, include."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithString("adapterOverrides", mcplib.Description("Keyed by agent slug. Safe imports reject the 'process' adapter — force opencode_local here (requires adapterConfig.")),
			mcplib.WithString("collisionStrategy", mcplib.Description("'replace' is NOT allowed on safe (board-key) imports")),
			mcplib.WithBoolean("include-agents", mcplib.Description("Agents")),
			mcplib.WithBoolean("include-company", mcplib.Description("Company")),
			mcplib.WithBoolean("include-issues", mcplib.Description("Issues")),
			mcplib.WithBoolean("include-projects", mcplib.Description("Projects")),
			mcplib.WithBoolean("include-skills", mcplib.Description("Skills")),
			mcplib.WithString("source", mcplib.Required(), mcplib.Description("Source")),
			mcplib.WithString("target", mcplib.Required(), mcplib.Description("Target")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/companies/{companyId}/imports/apply", false, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}, {PublicName: "adapterOverrides", WireName: "adapterOverrides", Location: "body"}, {PublicName: "collisionStrategy", WireName: "collisionStrategy", Location: "body"}, {PublicName: "include-agents", WireName: "agents", Location: "body", BodyPath: []string{"include", "agents"}}, {PublicName: "include-company", WireName: "company", Location: "body", BodyPath: []string{"include", "company"}}, {PublicName: "include-issues", WireName: "issues", Location: "body", BodyPath: []string{"include", "issues"}}, {PublicName: "include-projects", WireName: "projects", Location: "body", BodyPath: []string{"include", "projects"}}, {PublicName: "include-skills", WireName: "skills", Location: "body", BodyPath: []string{"include", "skills"}}, {PublicName: "source", WireName: "source", Location: "body"}, {PublicName: "target", WireName: "target", Location: "body"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_issues_create",
			mcplib.WithDescription("Create an issue. Required: companyId, title. Optional: assigneeAgentId, description, priority (plus 1 more)."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithString("assigneeAgentId", mcplib.Description("Assignee agent id")),
			mcplib.WithString("description", mcplib.Description("Description")),
			mcplib.WithString("priority", mcplib.Description("Priority")),
			mcplib.WithString("status", mcplib.Description("Status")),
			mcplib.WithString("title", mcplib.Required(), mcplib.Description("Title")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/companies/{companyId}/issues", false, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}, {PublicName: "assigneeAgentId", WireName: "assigneeAgentId", Location: "body"}, {PublicName: "description", WireName: "description", Location: "body"}, {PublicName: "priority", WireName: "priority", Location: "body"}, {PublicName: "status", WireName: "status", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_issues_list",
			mcplib.WithDescription("List issues. Required: companyId."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/companies/{companyId}/issues", true, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_projects_create",
			mcplib.WithDescription("Create a project. Required: companyId."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/companies/{companyId}/projects", false, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_projects_list",
			mcplib.WithDescription("List projects. Required: companyId."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/companies/{companyId}/projects", true, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_routines_create",
			mcplib.WithDescription("Create a routine (cron-scheduled task that wakes an agent — what makes a team run on its own). Required: companyId, title. Optional: assigneeAgentId, description, priority (default: medium) (plus 3 more)."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithString("assigneeAgentId", mcplib.Description("Assignee agent id")),
			mcplib.WithString("description", mcplib.Description("Description")),
			mcplib.WithString("priority", mcplib.Description("Priority")),
			mcplib.WithString("projectId", mcplib.Description("Project id")),
			mcplib.WithString("status", mcplib.Description("Status")),
			mcplib.WithString("title", mcplib.Required(), mcplib.Description("Title")),
			mcplib.WithString("triggers", mcplib.Description("Triggers")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/companies/{companyId}/routines", false, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}, {PublicName: "assigneeAgentId", WireName: "assigneeAgentId", Location: "body"}, {PublicName: "description", WireName: "description", Location: "body"}, {PublicName: "priority", WireName: "priority", Location: "body"}, {PublicName: "projectId", WireName: "projectId", Location: "body"}, {PublicName: "status", WireName: "status", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}, {PublicName: "triggers", WireName: "triggers", Location: "body"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("companies_routines_list",
			mcplib.WithDescription("List routines (each trigger's nextRunAt is the first fire). Required: companyId."),
			mcplib.WithString("companyId", mcplib.Required(), mcplib.Description("Company id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/companies/{companyId}/routines", true, false, nil, []mcpParamBinding{{PublicName: "companyId", WireName: "companyId", Location: "path"}}, []string{"companyId"}),
	)
	s.AddTool(
		mcplib.NewTool("issues_get",
			mcplib.WithDescription("Read an issue. Required: issueId."),
			mcplib.WithString("issueId", mcplib.Required(), mcplib.Description("Issue id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/issues/{issueId}", true, false, nil, []mcpParamBinding{{PublicName: "issueId", WireName: "issueId", Location: "path"}}, []string{"issueId"}),
	)
	s.AddTool(
		mcplib.NewTool("issues_update",
			mcplib.WithDescription("Update an issue (status. Required: issueId. Partial update."),
			mcplib.WithString("issueId", mcplib.Required(), mcplib.Description("Issue id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/api/issues/{issueId}", false, false, nil, []mcpParamBinding{{PublicName: "issueId", WireName: "issueId", Location: "path"}}, []string{"issueId"}),
	)
	s.AddTool(
		mcplib.NewTool("issues_comments_add",
			mcplib.WithDescription("Add a comment (this is how you 'chat' with an assigned agent — it wakes on new comments). Required: issueId, body."),
			mcplib.WithString("issueId", mcplib.Required(), mcplib.Description("Issue id")),
			mcplib.WithString("body", mcplib.Required(), mcplib.Description("Body")),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/api/issues/{issueId}/comments", false, false, nil, []mcpParamBinding{{PublicName: "issueId", WireName: "issueId", Location: "path"}, {PublicName: "body", WireName: "body", Location: "body"}}, []string{"issueId"}),
	)
	s.AddTool(
		mcplib.NewTool("issues_comments_list",
			mcplib.WithDescription("List comments. Required: issueId."),
			mcplib.WithString("issueId", mcplib.Required(), mcplib.Description("Issue id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/issues/{issueId}/comments", true, false, nil, []mcpParamBinding{{PublicName: "issueId", WireName: "issueId", Location: "path"}}, []string{"issueId"}),
	)
	s.AddTool(
		mcplib.NewTool("projects_get",
			mcplib.WithDescription("Read a project. Required: projectId."),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Project id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/projects/{projectId}", true, false, nil, []mcpParamBinding{{PublicName: "projectId", WireName: "projectId", Location: "path"}}, []string{"projectId"}),
	)
	s.AddTool(
		mcplib.NewTool("projects_update",
			mcplib.WithDescription("Update a project. Required: projectId. Partial update."),
			mcplib.WithString("projectId", mcplib.Required(), mcplib.Description("Project id")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/api/projects/{projectId}", false, false, nil, []mcpParamBinding{{PublicName: "projectId", WireName: "projectId", Location: "path"}}, []string{"projectId"}),
	)
	s.AddTool(
		mcplib.NewTool("routines_get",
			mcplib.WithDescription("Read a routine (incl. triggers/nextRunAt). Required: routineId."),
			mcplib.WithString("routineId", mcplib.Required(), mcplib.Description("Routine id")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/api/routines/{routineId}", true, false, nil, []mcpParamBinding{{PublicName: "routineId", WireName: "routineId", Location: "path"}}, []string{"routineId"}),
	)
	s.AddTool(
		mcplib.NewTool("routines_update",
			mcplib.WithDescription("Update a routine (title, triggers, status, assignee). Required: routineId. Optional: assigneeAgentId, description, priority (plus 3 more). Partial update."),
			mcplib.WithString("routineId", mcplib.Required(), mcplib.Description("Routine id")),
			mcplib.WithString("assigneeAgentId", mcplib.Description("Assignee agent id")),
			mcplib.WithString("description", mcplib.Description("Description")),
			mcplib.WithString("priority", mcplib.Description("Priority")),
			mcplib.WithString("status", mcplib.Description("Status")),
			mcplib.WithString("title", mcplib.Description("Title")),
			mcplib.WithString("triggers", mcplib.Description("Triggers")),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("PATCH", "/api/routines/{routineId}", false, false, nil, []mcpParamBinding{{PublicName: "routineId", WireName: "routineId", Location: "path"}, {PublicName: "assigneeAgentId", WireName: "assigneeAgentId", Location: "body"}, {PublicName: "description", WireName: "description", Location: "body"}, {PublicName: "priority", WireName: "priority", Location: "body"}, {PublicName: "status", WireName: "status", Location: "body"}, {PublicName: "title", WireName: "title", Location: "body"}, {PublicName: "triggers", WireName: "triggers", Location: "body"}}, []string{"routineId"}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='items'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
	BodyPath   []string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", v)
	}
}
func setNestedBodyArg(body map[string]any, path []string, value any) {
	if len(path) == 0 {
		return
	}
	if len(path) == 1 {
		body[path[0]] = value
		return
	}
	current := body
	for _, key := range path[:len(path)-1] {
		next, ok := current[key].(map[string]any)
		if !ok {
			next = map[string]any{}
			current[key] = next
		}
		current = next
	}
	current[path[len(path)-1]] = value
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				if len(binding.BodyPath) > 0 {
					setNestedBodyArg(bodyArgs, binding.BodyPath, v)
				} else {
					bodyArgs[binding.WireName] = v
				}
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export GOV_BOARD_KEY=<your-key>" +
					"\n      Run 'gov-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export GOV_BOARD_KEY=<your-key>" +
					"\n      Run 'gov-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export GOV_BOARD_KEY=<your-key>" +
					"\n      Run 'gov-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	trimmed := strings.TrimSpace(string(data))
	if strings.EqualFold(method, "GET") && len(trimmed) > 0 && trimmed[0] == '[' {
		var items []json.RawMessage
		if json.Unmarshal(data, &items) == nil {
			return mcplib.NewToolResultText(string(mcpBoundedListEnvelope("items", items, len(data))))
		}
	}
	if len(data) <= mcpToolResultMaxBytes {
		return mcplib.NewToolResultText(string(data))
	}
	if strings.EqualFold(method, "GET") {
		if out, ok := mcpBoundedSingleArrayObject(data); ok {
			return mcplib.NewToolResultText(string(out))
		}
	}
	return mcplib.NewToolResultText(string(mcpOversizedPreviewEnvelope(data)))
}

func mcpBoundedSingleArrayObject(data json.RawMessage) ([]byte, bool) {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return nil, false
	}
	arrayField := ""
	var items []json.RawMessage
	for key, raw := range obj {
		trimmed := strings.TrimSpace(string(raw))
		if len(trimmed) == 0 || trimmed[0] != '[' {
			continue
		}
		var candidate []json.RawMessage
		if json.Unmarshal(raw, &candidate) != nil {
			continue
		}
		if arrayField != "" {
			return nil, false
		}
		arrayField = key
		items = candidate
	}
	if arrayField == "" {
		return nil, false
	}
	build := func(subset []json.RawMessage) any {
		out := make(map[string]any, len(obj)+6)
		for key, raw := range obj {
			if key == arrayField {
				out[key] = subset
				continue
			}
			out[key] = raw
		}
		if len(subset) < len(items) {
			out["_pp_truncated"] = true
			out["_pp_total_count"] = len(items)
			out["_pp_returned_count"] = len(subset)
			out["_pp_original_bytes"] = len(data)
			out["_pp_max_bytes"] = mcpToolResultMaxBytes
			out["_pp_note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	out := mcpFitJSONItems(items, build)
	if len(out) > mcpToolResultMaxBytes {
		return nil, false
	}
	return out, true
}

func mcpBoundedListEnvelope(field string, items []json.RawMessage, originalBytes int) []byte {
	build := func(subset []json.RawMessage) any {
		out := map[string]any{
			"count": len(items),
			field:   subset,
		}
		if len(subset) < len(items) {
			out["truncated"] = true
			out["returned_count"] = len(subset)
			out["original_bytes"] = originalBytes
			out["max_bytes"] = mcpToolResultMaxBytes
			out["note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	return mcpFitJSONItems(items, build)
}

func mcpFitJSONItems(items []json.RawMessage, build func([]json.RawMessage) any) []byte {
	limit := len(items)
	if limit > mcpToolResultMaxItems {
		limit = mcpToolResultMaxItems
	}
	for n := limit; n >= 0; n-- {
		out, err := json.Marshal(build(items[:n]))
		if err != nil {
			continue
		}
		if len(out) <= mcpToolResultMaxBytes || n == 0 {
			return out
		}
	}
	out, _ := json.Marshal(build(items[:0]))
	return out
}

func mcpOversizedPreviewEnvelope(data json.RawMessage) []byte {
	previewBytes := data
	if len(previewBytes) > 4000 {
		previewBytes = previewBytes[:4000]
	}
	out, _ := json.Marshal(map[string]any{
		"truncated":      true,
		"original_bytes": len(data),
		"max_bytes":      mcpToolResultMaxBytes,
		"preview":        string(previewBytes),
		"note":           "Typed MCP endpoint response exceeded the tool result budget and was not a recognized list envelope. Narrow the request with filters, search/sql, or a command-mirror tool with --agent/--compact/--select.",
	})
	return out
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "gov-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "gov-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	return toolResultJSON(results)
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}

	return toolResultJSON(results)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "gov",
		"description": "The verified subset of the Paperclip board API used to spin up and manage teams of AI agents — whole businesses",
		"archetype":   "project-management",
		"tool_count":  24,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion gov-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "GOV_BOARD_KEY",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "agents",
				"description": "Manage agents",
				"endpoints":   []string{"delete", "get", "update"},
				"searchable":  true,
			},
			{
				"name":        "companies",
				"description": "Manage companies",
				"endpoints":   []string{"create-company", "get-company", "list", "update-company"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "issues",
				"description": "Manage issues",
				"endpoints":   []string{"get", "update"},
				"searchable":  true,
			},
			{
				"name":        "projects",
				"description": "Manage projects",
				"endpoints":   []string{"get", "update"},
				"searchable":  true,
			},
			{
				"name":        "routines",
				"description": "Manage routines",
				"endpoints":   []string{"get", "update"},
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Finding stale work", "insight": "Use the stale command or sql query to find items not updated recently. More reliable than scanning list results manually."},
			{"topic": "Load analysis", "insight": "When analyzing team workload, filter by assignee and status. Raw counts without status filtering are misleading."},
			{"topic": "Bulk operations", "insight": "For bulk status changes, prefer update endpoints over delete+create. Most PM APIs track history on updates."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
