// Copyright 2026 jbellsolutions and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type AdapterConfig struct {
	Cwd   string          `json:"cwd"`
	Env   json.RawMessage `json:"env"`
	Model string          `json:"model"`
}

type Agent struct {
	AdapterConfig      json.RawMessage `json:"adapterConfig"`
	AdapterType        string          `json:"adapterType"`
	BudgetMonthlyCents int             `json:"budgetMonthlyCents"`
	CompanyId          string          `json:"companyId"`
	Id                 string          `json:"id"`
	Name               string          `json:"name"`
	ReportsTo          string          `json:"reportsTo"`
	Role               string          `json:"role"`
	SpentMonthlyCents  int             `json:"spentMonthlyCents"`
	Status             string          `json:"status"`
	Title              string          `json:"title"`
}

type AgentCreate struct {
	AdapterConfig      json.RawMessage `json:"adapterConfig"`
	AdapterType        string          `json:"adapterType"`
	BudgetMonthlyCents int             `json:"budgetMonthlyCents"`
	Name               string          `json:"name"`
	ReportsTo          string          `json:"reportsTo"`
	Role               string          `json:"role"`
	Title              string          `json:"title"`
}

type AgentUpdate struct {
	AdapterConfig      json.RawMessage `json:"adapterConfig"`
	AdapterType        string          `json:"adapterType"`
	BudgetMonthlyCents int             `json:"budgetMonthlyCents"`
	ReportsTo          string          `json:"reportsTo"`
	Status             string          `json:"status"`
	Title              string          `json:"title"`
}

type CommentCreate struct {
	Body string `json:"body"`
}

type Company struct {
	BudgetMonthlyCents int    `json:"budgetMonthlyCents"`
	Description        string `json:"description"`
	Id                 string `json:"id"`
	IssuePrefix        string `json:"issuePrefix"`
	Name               string `json:"name"`
	SpentMonthlyCents  int    `json:"spentMonthlyCents"`
	Status             string `json:"status"`
}

type CompanyCreate struct {
	Description string          `json:"description"`
	Metadata    json.RawMessage `json:"metadata"`
	Name        string          `json:"name"`
}

type CompanyUpdate struct {
	BudgetMonthlyCents int    `json:"budgetMonthlyCents"`
	Description        string `json:"description"`
	Name               string `json:"name"`
	Status             string `json:"status"`
}

type Import struct {
	AdapterOverrides  json.RawMessage `json:"adapterOverrides"`
	CollisionStrategy string          `json:"collisionStrategy"`
	Include           json.RawMessage `json:"include"`
	Source            string          `json:"source"`
	Target            string          `json:"target"`
}

type IssueCreate struct {
	AssigneeAgentId string `json:"assigneeAgentId"`
	Description     string `json:"description"`
	Priority        string `json:"priority"`
	Status          string `json:"status"`
	Title           string `json:"title"`
}

type RoutineCreate struct {
	AssigneeAgentId string          `json:"assigneeAgentId"`
	Description     string          `json:"description"`
	Priority        string          `json:"priority"`
	ProjectId       string          `json:"projectId"`
	Status          string          `json:"status"`
	Title           string          `json:"title"`
	Triggers        json.RawMessage `json:"triggers"`
}

type RoutineTrigger struct {
	CronExpression string `json:"cronExpression"`
	Enabled        bool   `json:"enabled"`
	Kind           string `json:"kind"`
	Timezone       string `json:"timezone"`
}
